### PR TITLE
Revert "Exit with non-zero when we fail to fetch cache"

### PR DESCRIPTION
**Pull request by amanya**
This reverts commit 7e3ffb6627ecbc9d52ac94b0033ebd3bc8c52d46.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Sorry, but we shouldn't merge to the `production` branch as a matter of principle.

**Comment by amanya** [comment]
Ok, and what we should do to use the modified script from our system? (Travis enterprise)

**Comment by BanzaiMan** [comment]
@amanya I've merged the other PR, updated the `production` branch here, so I believe it is available to you now.

**Comment by amanya** [comment]
Ok, thanks!

**Pull request closed without merging**
