### PR TITLE
Test on OS X

### PR DESCRIPTION
**Pull request by PlasmaPower**
Should help prevent problems like https://github.com/travis-ci/travis-ci/issues/8657

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Unfortunately, it does not.

**Comment by PlasmaPower** [comment]
Oh yeah, look like the tests need some improvements.

**Comment by BanzaiMan** [comment]
Indeed. They do. :-)

As I explained in https://github.com/travis-ci/travis-ci/issues/8657#issuecomment-340191946, the cause of the issue was that some images do not have `sudo` set up correctly. It would have required some extensive end-to-end testing for this to be detected.

**Comment by PlasmaPower** [comment]
Merged into #32

**Pull request closed without merging**
